### ISSUE TITLE
Seperate Blips for Police [Enhancement] [Suggestion]

### ISSUE THREAD

**Issue by XxROBOTICSxX** [TGRHavoc/live_map-interface#12]
Have the resource use the IS_PED_IN_ANY_POLICE_VEHICLE native to allow the map interface to display players in police vehicles as a different color car icon (such as blue). With this also including settings so that you can have the map display only certain things. Example: All Players, Only Players in Cars, Only Players on Foot, Only Police Vehicles, etc.

**Comment by TGRHavoc** [comment]
> Have the resource use the IS_PED_IN_ANY_POLICE_VEHICLE native to allow the map interface to display players in police vehicles as a different color car icon (such as blue). 

Going to be honest, not something I want to add to the map. This was never meant to be a RP resource and I only really want to implement features that will benefit everyone not just the RP community. Feel free however, to modify it as you want and add this feature yourself. You can look in the default "client.lua" file to see how you can change the player's icon with the "IS_PED_IN_ANY_POLICE_VEHICLE" native. You can set it to the police icon (id=56) (and modify the texture sheet) or, set the icon to PoliceStation (id=60) which, is already blue.

> With this also including settings so that you can have the map display only certain things. Example: All Players, Only Players in Cars, Only Players on Foot, Only Police Vehicles, etc.

This has been something else I've been meaning to implement as well, along side the other blip controls (only showing certain blips).

**Comment by davwheat** [comment]
In addition (somewhere in some piece of code i saw earlier) if you have custom add-on vehicles, you can check for the specific model name and set the specific blip there.

**Comment by XxROBOTICSxX** [comment]
I have found a solution to my needs, I edited the texture of icon 56 to suit my needs, and have added my add-on vehicles into the section that checks for police vehicles. No issues thus far, Thanks for your assistance.

**Comment by davwheat** [comment]
Nice
