### ISSUE TITLE
Can't load live_map-interface-master 

### ISSUE THREAD

**Issue by MichonH** [TGRHavoc/live_map-interface#19]
For some reason when I start up the server and when I try to join I get the message.
And there is no error in the logs that I can find.

**Comment by MichonH** [comment]
![image](https://user-images.githubusercontent.com/43234280/45477169-2716f600-b76b-11e8-966c-232c7edb1cf4.png)

**Comment by MichonH** [comment]
Oh sorry, But how do I open the site?

**Comment by TGRHavoc** [comment]
Clone the repo onto a server that has a web server (e.g. nginx, Apache, iis) installed with PHP support. Point the webserver to the directory you cloned the repo into, and you're good to go. All you need to do now is download and extract the images and make sure you configure it properly.

**Comment by MichonH** [comment]
Uhm I am kinda confused on what to do

**Comment by MichonH** [comment]
So i've configured Config file and the Index file, what should I do not?

**Comment by TGRHavoc** [comment]
> So i've configured Config file and the Index file, what should I do now?

Upload the files to a web server. If you have no idea what you're doing then may I suggest you either get someone who does to help you or, not use this resource.

> Is there a video about how to do it?

No. And I don't really have the time at the minute to make one either.
