### ISSUE TITLE
Reduce images

### ISSUE THREAD

**Issue by TGRHavoc** [TGRHavoc/live_map-interface#22]
So, currently the amount of images needed to get the map working is ridiculous. Maybe with the new map API re-write we can use the images from GTA itself rather than relying on the current set of images.

It would also allow people to make their own map images (using the GTA ones as a template) and add it to the map much easier.

For example, if they wanted the "post code" map all they would have to do is export the texture and put them in a folder.

It would also reduce the image size from 200+ MB (megabytes) to about 5 MB.

**Comment by matsn0w** [comment]
Any updates on this? How did you generate the map? Can I do that myself?

**Comment by TGRHavoc** [comment]
@matsn0w 

The plan is to use GTA's map images exported from their YTD formats to PNG. This would then allow people to export custom YTD files for their postal maps. An example would be [FiveMPostalMap](https://github.com/txarmyowens/FiveMPostalMap/tree/master/Server%20Side/map/stream) from @txarmyowens.

If not, users would be able to edit the PNG's instead. Which would be a lot easier as their's only like 4 images and not 500+ like their currently is.

> Any updates on this?

I started to implement the new API the other day and I have exported the default GTA map images for testing.

> How did you generate the map?

The current images were taken from a website, not too sure how they generated the images though.

> Can I do that myself?

With the new system coming out, yes. All you'd need is OpenIV (or similar software) to export the YTD to PNG images.

**Comment by matsn0w** [comment]
Cool, thanks for your quick reply! Currently implementing your map in my RP clan's server.

**Comment by Starystars67** [comment]
Any update on this as would be nice to get a postcodes map working for dispatch for example.

**Comment by TGRHavoc** [comment]
@Starystars67 yes sir. Just need to implement other stuff now but, if you want to check it out (with no features at all) switch to the development branch (you will need to extract the minimap_sea images from GTA and configure the JS in index.php to get it to work).

There's also a video of the new map working over on another issue: https://github.com/TGRHavoc/live_map-interface/issues/20#issuecomment-454129912
