### ISSUE TITLE
Firetruck and ambulance are recognised as 'Unknown vehicle'

### ISSUE THREAD

**Issue by ReaverM** [TGRHavoc/live_map-interface#25]
I am having an issue with ambulances and firetrucks where they are recognized as unknown vehicles and not as either an ambulance or firetruck.

**Comment by itismejoey** [comment]
I am going to assume that you’re using addon vehicles? If so, you need to add these vehicles to the car hashes file.

**Comment by davwheat** [comment]
You can also specify the names of the vehicles as whatever you want in the
vehicles meta file.

**Comment by ReaverM** [comment]
Nope, i am just talking about the normal ambulance and firetruck. Police vehicles work, even the add-on vehicles I added to the car hashes file, but ambulances and firetrucks (even the ones that are in gta v) are not recognised

**Comment by ReaverM** [comment]
I found a way around this by adding them to another vehicle sprite in the client, so adding or vehicleModel == h("ambulance") to for example the armored truck sprite
