### ISSUE TITLE
LiveMap stops updating and causing timeouts

### ISSUE THREAD

**Issue by JasonO99** [TGRHavoc/live_map-interface#26]
Currently, I use this on a server that can have 20-30 players running latest Linux stable build.
Web server and Gameserver are on different servers as I don't have a web server option on the FiveM server. I'm running the latest stable build of the live map resource and web pages.

I can't 100% confirm, but when it is busy sometimes a person loading the live_map can cause 30-70% of the players to timeout. I've not been able to replicate it every time, but on 2 occasions where I've got someone to load the live_map having it not being loaded for 10 minutes or so caused timeouts on most of the server within 5 seconds of it being clicked. Unsure why.

Secondly, there are times where all the markers stop moving although page still shows connected, even after refreshing the page. A restart of the live_map resource and then restart of the web page fixes it. I'm unsure if the more people looking at the live map can expedite how quickly this bug is? Again it's random and difficult to replicate. Sometimes I can go through 2 hours of it not doing this, sometimes it can happen within minutes of restarting. 

I appreciate this is a bit of a shit, vague report - is there anything I can do that may indicate to me what is causing the problem? FiveM logs show no errors at all. Server performance never exceeds 30% RAM/CPU and no other lag exists on the server. If there's anything I can do to obtain more information for you do let me know.

PS - I've not a feckin clue how to add icons/badges to this post - Github newbie.

**Comment by JasonO99** [comment]
I've uploaded 3.2.0 and will be testing this over the week to see if this issue still occurs. #

**Comment by TGRHavoc** [comment]
> I've uploaded 3.2.0 and will be testing this over the week to see if this issue still occurs. #

It will... Or at least it should... I haven't touched the C# side of the resource yet (the side you're having issues with).

**Comment by JasonO99** [comment]
Indeed it does still occur. I shall wait for an update on the FiveM resource side of things. If the problem is irrelevant to the interface then I'll close and await an update to the framework side of it.
