### ISSUE TITLE
Better config

### ISSUE THREAD

**Issue by TGRHavoc** [TGRHavoc/live_map-interface#28]
At the moment people have to configure the map via the `config.php` file. I think this is causing confusion with some people thinking the IP's can be local addresses (e.g. 127.0.0.1).

Instead, maybe the config should be in a JSON/YAML file.

Thoughts?

**Comment by matsn0w** [comment]
Maybe just build a simple GUI?

**Comment by TGRHavoc** [comment]
> Maybe just build a simple GUI?

I _could_ possibly do this for the JSON file. A basic HTML file where one can enter the config details and, it spews out the JSON you need to paste into the config file... If that's what you mean.

It would be a HTML file because it wouldn't edit the JSON file directly. This would be a security issue, where anyone who could access the page could edit the config on the server.

**Comment by davwheat** [comment]
It doesn't HAVE to be a security problem. It could only be accessed by
localhost (small issue for anything but VPSes), a set range of IP addresses
(not useful for people who change devices/need to access phone their mobile
data), username/password set in config (if found, could be dangerous), or
it could lock itself when not needed.

Or.... it could just be what you suggested :P

**Comment by TGRHavoc** [comment]
Added in 9f995c0b9a3e7eb9519f2483e9ae3b788f0310cc. Going to make a new issue for the "config generator" thing.
