### ISSUE TITLE
Configuration to toggle the grouping option

### ISSUE THREAD

**Issue by JasonO99** [TGRHavoc/live_map-interface#32]
Really like the design and what you've done with 3.2.0.

Is it possible,  or if not could it be possible to toggle the grouping of the markers? I can see why it was requested and implemented but individually for our server we would prefer to see the individual markers.

The interface overall certainly feels a lot quicker and response compared to the Google Maps engine.

**Comment by TGRHavoc** [comment]
Implemented in 18ff8282584c84e8b9f5b4f15303fb4adfa0a80c
