### ISSUE TITLE
Not showing player Blips

### ISSUE THREAD

**Issue by XxModZxXWiiPlaza** [TGRHavoc/live_map-interface#36]
Hello. I am able to get the locations Icons but I am not able to get the player blips to work I am getting the error 

" Socket error! There was an error with the socket connection: Unknown reason (Server is probably down)" 

But now nothing is showing up when ever I changed my config. Anyway you can help me out if needed we can add each other on discord

**Comment by TGRHavoc** [comment]
Most likely a network issue. Make sure you have correctly opened your ports for the websocket connection.
