### ISSUE TITLE
Cant display livemap when using HTTPS

### ISSUE THREAD

**Issue by DayZen16** [TGRHavoc/live_map-interface#37]
I am currently able to access the livemap if i do a direct ip on non https. However the whole site is on  https and livemap will not load.

**Comment by TGRHavoc** [comment]
Yep. That's how that works... The resource can't magically make a secure connection to FiveM.... It's impossible.

That's where "proxies" come in handy. If you have no idea what I'm talking about, or even what webserver you're running on. Just uninstall the resource and have a nice day.

If you do, then just Google "set up reverse proxy in <webserver>". Obviously substituting with the webservers name. And to get the websocket running securely as well, just change the query to "set up websocket revserse proxy in <webserver>".

**Comment by DayZen16** [comment]
I gotcha. Appreciate it.
