### ISSUE TITLE
Language support?

### ISSUE THREAD

**Issue by Malaros** [TGRHavoc/live_map-interface#39]
Hello, how can i change the language of the map? 

Thanks <3

**Comment by TGRHavoc** [comment]
There currently is no way of doing this unless you go through the files yourself and translate the stuff you need into the language of your choice. 

It would be nice to have language support in the interface. I could work on something but, it would take a while to get it done and ready for general use

**Comment by Malaros** [comment]
Where can i change it? Which file?

**Comment by TGRHavoc** [comment]
mainly the  [https://github.com/TGRHavoc/live_map-interface/blob/master/index.html](index.html) file but, there's text everywhere through the JS files as well

**Comment by TGRHavoc** [comment]
Implemented in the following commits:
d2050aeca56fbd9f30f3bcad4a1902fa53567360
6ff88be649366cfb34c6dbb14073e15bb3c8900a
e9b27e1211c704829317ef3f64c18a9e7b617356
b6fa62e658ba5f09fc5a4e38c77e11636ca46740
9caff2c54ef8f523d2699120c00bd7b8c0376b8f

If you want your language to be added, then you will need to translate the following JSON file:
```json
{
    "title" : "Havoc's LiveMap",
    "credit": "This was originally created by ",
    "navbar":{
        "select-server" : "Select a server",
        "controls" : "Show Controls",
        "blips": "Blip controls",
        "language": "Language"
    },
    "generic": {
        "on" : "On",
        "off" : "Off",
        "connected" : "Connected",
        "disconnected": "Disconnected",
        "close": "Close"
    },
    "controls" : {
        "title" : "Controls",
        "blips" : {
            "title" : "Blips",
            "refresh": "Refresh Blips",
            "show" : "Show Blips"
        },
        "connection": {
            "title": "Connections",
            "live-update": "Live Update",
            "reconnect" : "Reconnect"
        },
        "information": {
            "title": "Information",
            "viewing": "Currently viewing",
            "blips-loaded": "Blips loaded",
            "players": "Player Count"
        },
        "track-player": "Track a player",
        "filter": {
            "title": "Filter",
            "filter-value": "With a value of",
            "filter-placeholder": "Some value"
        }
    },
    "blip-controls": {
        "title": "Blip Controls",
        "toggle": "Toggle all"
    }
}
```

If you wan to add it your self, just add a new JSON file under the "translations" directory with the name `{{language_code}}.json` (Where language code can be found at https://www.science.co.il/language/Locale-codes.php).

Then, just add it to the `manifest.json` file for users to be able to use it. With the language code as the key and the name of the language (in it's own language) as the value.
```json
{
    "en": "English", 
   "es": "Español"
}
```
