### ISSUE TITLE
Add road names

### ISSUE THREAD

**Issue by TGRHavoc** [TGRHavoc/live_map-interface#4]
Would be nice to have the road names displayed on the map when the user zooms in

**Comment by davwheat** [comment]
I've got a custom map that has post codes xD

**Comment by TGRHavoc** [comment]
> I've got a custom map that has post codes xD

You want to send me it through Discord? I'll update the image release to include it and, update the code so people can use it 😃

**Comment by davwheat** [comment]
Happily, It's not quite finished, though, which is disappointing. Also it's a bit... how should I put this... not that great...

**Comment by TGRHavoc** [comment]
> Happily, It's not quite finished, though, which is disappointing. Also it's a bit... how should I put this... not that great...

OK.. If you want, you can send it when it's too a standard you like 😄

**Comment by davwheat** [comment]
In addition, it'd need a bit of work before it is released, as it's got some stuff from a role-play community I was in, like Heathrow Airport instead of LSIA, and NHS instead of a generic hospital icon (only bc the people who hosted it couldn't be arsed to create the blips manually).

**Comment by davwheat** [comment]
![image](https://user-images.githubusercontent.com/7406822/33224937-05088fd2-d167-11e7-8641-9761c9f2a63d.png)
![image](https://user-images.githubusercontent.com/7406822/33224943-10de7560-d167-11e7-8c27-260f527c41e3.png)

**Comment by davwheat** [comment]
Just some images so you know what it's like. If I were to edit it, I'd probably just add the street names anyway...

**Comment by XxROBOTICSxX** [comment]
What is the status of this? I would really like to see this implemented as soon as possible as it is a great feature.

**Comment by TGRHavoc** [comment]
@XxROBOTICSxX

Just be patient. There's no ETA on this as it takes time to implement and at the moment, the guy implementing it is busy with exams (and so am I). So, not ETA. It will be done when it's done.

**Comment by TGRHavoc** [comment]
This has been kind of implemented on the resource as of [25fef3889a](https://github.com/TGRHavoc/live_map/commit/25fef3f889a218f9ba0bfc97432ffc8deed619ce).

If/When davwheat has completed the images I will add them to this repo instead of the current implementation.

**Comment by ReaverM** [comment]
Is the postcode map available anywhere? Or has it not been implemented yet?
