### ISSUE TITLE
Suggestion/Question

### ISSUE THREAD

**Issue by GameLoverNL** [TGRHavoc/live_map-interface#42]
Hey!

I want to integrate a system so that I can set a waypoint in the livemap that will be set for a user selected with a dropdown and will set a GPS route in-game for ONLY that user who is selected, so kinda the same system as tracking a player but then with setting a waypoint for a player (Probably with a SET_WAYPOINT native?). Is this something that can be made in the existing interface or can someone give me some information on how I can do it myself? 

Thanks in advence :)

This is a suggestion no error.

**Comment by TGRHavoc** [comment]
Not in the scope for this plugin. You can modify the original resource to accept data from the websocket but, will need to understand the risks that come with allowing _anyone_ to send data to your server and control waypoints for users in game.
