### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by TGRHavoc** [TGRHavoc/live_map-interface#47]
At the moment the documentation is one page.

The readme.. That's it. Instead the documentation should be split up into digestible files.

For example:
- `config.md` - Contains information about configuring the interface (since it's pretty extensive).
- `faq.md` - Frequently asked questions about the interface. On the resource, maybe this should also contain information about running `npm/yarn` manually if it fails to start on it's own?

Etc.

**Comment by DaveOkpare** [comment]
Hi @TGRHavoc, I'm new here. Can I work on this?

**Comment by TGRHavoc** [comment]
@DaveOkpare
If you're still interested in this, I would happily accept your help!

Just a heads up, I settled on having a "docs" folder that contains said documentation. I feel it makes it easier to find the documentation as its all in one place when they clone the repo.

See https://github.com/TGRHavoc/live_map-interface/tree/develop/docs

Just let me know if you're still wanting to work on this :)

**Comment by DaveOkpare** [comment]
@TGRHavoc  I'm very much interested on organizing the documentation.


Quick question:
- `faq.md` - Where should I get the `npm/yarn` information from?

**Comment by TGRHavoc** [comment]
> @TGRHavoc I'm very much interested on organizing the documentation.
> 
> Quick question:
> 
> * `faq.md` - Where should I get the `npm/yarn` information from?

I think that would be more suited for the resource documentation since that's where non-developers would need to use npm/yarn. But it would probably under a heading like "The resource won't start" and maybe showing a screenshot of the error they would see in console.

For the interface I think you could probably find issues that people have had and what's solved it and pop them into the FAQ... If I think of anything else I can always pop them here.

As for the documentation for the interface, I have an idea of what files would be nice to have:
- `developers.md` - Developer information. Cloning the repo, installing the dependencies in package.json with NPM/YARN
  - NPM: See https://www.npmjs.com/get-npm. After it's installed `npm install`
  - Yarn requires NPM anyways so, might be good to just go over npm.
  - What lives where (`js/src` for js files, `style/scss` for css)
-  `faq.md` - Stuff people have had issues with. E.g. Diagnosing `error getting blips` etc.
- `config.md` - How to configure the interface. Might be good to mention the config.html page when that's up to a better standard.
- `reverse_proxy.md` - How to set up various reverse proxies to secure livemap. 
  - Might be worth only doing NGINX/Apache since they seem to be the most popular webserver's
  - Maybe also tell users how to configure it in the livemap with real examples (might be easier to see the config.json next to their webserver configs so they understand a bit better).
- `custom_maps.md` - How they can get their custom map images into livemap.
  - Step 1 - Extract YTD from GTA or whereever
  - Step 2 - Installing [Pillow](https://pypi.org/project/Pillow/)
  - Step 3 - Running the python script `images/tiles/extract_png.py`
  - Step 4 - Configure the map

That's all I can think of at the moment. And I've just realised it's quiet a lot 😆 
If you don't feel comfortable doing something, get stuck or anything else, let me know. I'll try and help you the best I can.

**Comment by TGRHavoc** [comment]
I feel like this has sufficiently been completed by @DaveOkpare.

See #49, #50 & #51.

Currently lives on the [develop](https://github.com/TGRHavoc/live_map-interface/tree/develop/docs) branch and the new documentation website (https://docs.tgrhavoc.co.uk/livemap-interface).

If anything new needs adding to the documentation or anything needs changing then, a new issue should be created.
