### ISSUE TITLE
Re-do interface

### ISSUE THREAD

**Issue by TGRHavoc** [TGRHavoc/live_map-interface#48]
Overhaul the interface. Making sure it's atleast 90% mobile compatible.

At the moment, the interface works on mobile but, it's not very pleasant.
I want people to be able to use the interface on mobile if they want (i know the majority of users are on desktop and this is probably a moot point).

**Comment by Local9** [comment]
> majority of users are on desktop

I have cross party users now days, even if they are on Desktop, they use their mobile for Discord or various other things as they may not have two monitors or dislike ALT+TAB'in around. So I will happily support this happening.

**Comment by TGRHavoc** [comment]
> I have cross party users now days, even if they are on Desktop, they use their mobile for Discord or various other things as they may not have two monitors or dislike ALT+TAB'in around. So I will happily support this happening.

Yeah. What's your thoughts on having the controls in a scrollable modal?

I feel like this would be the best approach for the mobile part as it should show nearly full screen.

Example of what it would look like (just imagine if the controls were in there and not the random text, haven't got around to moving them yet):

![Desktop](https://user-images.githubusercontent.com/1770893/118412400-9cac9000-b691-11eb-9584-67301515e47d.png)
![Mobile](https://user-images.githubusercontent.com/1770893/118412409-a9c97f00-b691-11eb-8d06-cf7691d02e07.png)

**Comment by TGRHavoc** [comment]
Woop 🎊 

![c2e254121cd2a69eae14d70b5a43e1c5221cea890cf174d2ba1ae58d3712](https://user-images.githubusercontent.com/1770893/118742495-6c5b2200-b848-11eb-8b3a-9ef9ef43a0f7.gif)

I can now continue on getting the JavaScript functional again.
