### ISSUE TITLE
Leaflet 404 error

### ISSUE THREAD

**Issue by Aaron-Downham** [TGRHavoc/live_map-interface#63]
**Describe the bug**
Updated to v4.1.0, the page is white and the console is filled with multiple 404 errors for images which I'm assuming Leaflet is supposed to generate as there are a lot more than the base 6 minimap PNGs.

**To Reproduce**
Completely wiped the previous interface files (except config and images folder) and downloaded the new files from the release page on GitHub

**Expected behavior**
Page should load

**Screenshots**
https://downham.dev/i/9h5yd.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (Tried Edge and Firefox too)
 - Version [e.g. 22]: 91.0.4472.77 (Official Build) (64-bit)

**Comment by TGRHavoc** [comment]
Could you hard reload the page for me to see if its the browser's cache? `CTRL + SHIFT + R` should be enough?

**Comment by Aaron-Downham** [comment]
Yeah tried that, should have said sorry - same issue happens if I switch back to the default config

**Comment by TGRHavoc** [comment]
Okay.
1) Is that the only error on that page?
2) Does debug.html work as intended?

**Comment by Aaron-Downham** [comment]
Yes that's the only error, the page is functionally working as I can see the player list if I mess about: https://downham.dev/i/jy3gy.png

Debug page: https://downham.dev/i/r2oy4.png

**Comment by TGRHavoc** [comment]
> https://downham.dev/i/jy3gy.png
That's showing the old controls... Are you sure its not the browser cache or even a CDN you might have in front of the website (I.e. cloudflare).
If you do, you might want to purge their cache to see the latest interface.
Even the second screenshot shows the older directory for the JS files...

**Comment by Aaron-Downham** [comment]
We do use cloudflare, clearing the cache hasn't done anything so I don't think it's that. 

What should the new directory layout look like out of curiosity? I completely deleted the old version before uploading the files in the v4.1.0 release

**Comment by TGRHavoc** [comment]
The JS files should just be served from `js/src` rather than the `js/src/(last|first)_bundle` we're seeing.

Are you sure you downloaded 4.1.0? Because the version.json file says it's 4.0.1 (which is a broken version).

![image](https://user-images.githubusercontent.com/1770893/121408031-d3578c80-c957-11eb-84ff-6ea71bf58de0.png)

**Comment by Aaron-Downham** [comment]
https://downham.dev/i/b9r24.png

I've just downloaded it again to be sure and the release file has version 4.0.1 in the version.json, not sure what's happened there

**Comment by Aaron-Downham** [comment]
I've put Cloudflare into a development mode to bypass the cache for now

**Comment by TGRHavoc** [comment]
Right, the latest release should have the correct files in it now 🎊

**Comment by TGRHavoc** [comment]
@all-contributors please add @Aaron-Downham for bug 

@Aaron-Downham I'm going to close this issue now as I think I've fixed the issue. Thanks for the report and, if you have any issues don't hesitate to make a new one :smile:
