### ISSUE TITLE
Interface fails to load over HTTPS

### ISSUE THREAD

**Issue by MisterDarkSideYT** [TGRHavoc/live_map-interface#72]
If i install the interface and the resource i get this error. i can't fix it :|

Error loading config, failed to fetch

**Comment by TGRHavoc** [comment]
The interface cannot find the config file. Make sure its available on your website (can be done by going to `http://your_website/config.json`)

**Comment by MisterDarkSideYT** [comment]
it stay on domain.nl/livemap/config.json because livemap stay in an another site

**Comment by TGRHavoc** [comment]
The config needs to be in the same place as the index.html. Putting it on another website won't work?

**Comment by MisterDarkSideYT** [comment]
Iknow that. The index.html from this resource and the config.json (renamed from config.example.json) are in the same folder named livemap

**Comment by TGRHavoc** [comment]
Hmm. Want to email me the URL so I can double check?  jordan@tgrhavoc.co.uk.

If not, can you load `debug.html` with your browser's console open to see if there's any errors? Generally the "network" tab should give you a URL that its looking for, the console might even throw an error that we can use to see why it isn't working :)

**Comment by MisterDarkSideYT** [comment]
Okay. Tomorrow i will check it.

**Comment by MisterDarkSideYT** [comment]
![Schermopname (447)_LI](https://user-images.githubusercontent.com/79758423/124307422-1b895980-db68-11eb-85e4-34f526964946.jpg)

**Comment by TGRHavoc** [comment]
Ah. If you want to use HTTPS you will need to set up a reverse proxy for the blips and socket.

https://docs.tgrhavoc.co.uk/livemap-interface/reverse_proxy/

**Comment by MisterDarkSideYT** [comment]
do i place it in the server.cfg (FiveM side) or in config.json (website side)

**Comment by TGRHavoc** [comment]
You need to co figure your webserver to have the reverse proxy. If you're hosting the website on a Windows server this is usually IIS. If your website is hosted by a hosting company (e.g. 000webhosts) then you will either need to ask them to set up a reverse proxy for you or, disable HTTPS.

**Comment by MisterDarkSideYT** [comment]
it stay on a linux vps

**Comment by MisterDarkSideYT** [comment]
no windows, no hosting company like webhosting

**Comment by TGRHavoc** [comment]
Okay, you _might_ have nginx then. Best bet is to ask the guy who set up your website for you and ask them to set up a reverse proxy for you?

If you want to do this yourself, there is a [beginners guide to configure nginx](http://nginx.org/en/docs/beginners_guide.html). Again, this is assuming you are using nginx...

**Comment by MisterDarkSideYT** [comment]
they don't know what i mean with reverse proxy

**Comment by TGRHavoc** [comment]
Um, you can try sending them a link that explains it to them,
https://www.cloudflare.com/en-gb/learning/cdn/glossary/reverse-proxy/
In simple terms it'll allow you to make your insecure connection over a secure connection.

If they aren't using nginx then, they can google how to set one up using the webserver.
If they're still having issues then, it might be easier to just move the website to normal HTTP.

**Comment by MisterDarkSideYT** [comment]
with http you don't need a reverse proxy?

**Comment by TGRHavoc** [comment]
Correct :)

**Comment by MisterDarkSideYT** [comment]
okay thank you

**Comment by TGRHavoc** [comment]
No problem. Once you've got it working, you can close this issue if you want or I'll close it after a couple of days :)

**Comment by MisterDarkSideYT** [comment]
yeah i look when its working

**Comment by MisterDarkSideYT** [comment]
Do you have discord so you can help me with reverse proxy because i don't know how to make it.

**Comment by TGRHavoc** [comment]
Sure, it's Havoc#4592. I can only stay on for an hour or so today though.
