### ISSUE TITLE
Server connects with interface but players do not show. At least I think it connects

### ISSUE THREAD

**Issue by camonwii** [TGRHavoc/live_map-interface#76]
I am using this livemap on a http webserver and I've configured it correctly into the config on the webserver. 

```
{
    "debug": true,
    "tileDirectory": "images/tiles",
    "iconDirectory": "images/icons",
    "showIdentifiers": true,
    "groupPlayers": true, // Wether the map should group players together into "clusters" or not.
    "defaults": { // If a server doesn't have the key-value set, it will fallback to these values
        "ip": "IP", // Make sure this is the PUBLIC IP of the FIVEM server
        "socketPort": "30121" // Set to the port that you set in the "socket_port" convar (if different to the one in the config)
    },
    "servers": {
        "Server 1": {} // The config values are above, no need to write them again
    },
    "maps": [
        {
            "name": "Normal",
            "url": "{tileDirectory}/normal/minimap_sea_{y}_{x}.png",
            "minZoom": -2 // Set lower to zoom out more
        },
        {
            "name": "Postal",
            "url": "{tileDirectory}/postal/minimap_sea_{y}_{x}.png",
            "minZoom": -5 // Since this is 3 times bigger, just remove 3 from the default minZoom
        }
    ]
}
```
This is my config setup on the webserver and my server.cfg convar for the resource looks like this:

```
set socket_port 30121
set livemap_debug "all" # "[all]" 'trace', 'debug', 'info', 'warn', 'error', 'fatal', 'off'
set blip_file "server/blips.json"
set livemap_access_control "*"

ensure livemap
```
and it's setup at the top of the resource section of the .cfg

I have 0 clue why it's not showing players but it connects. It worked about a week ago, then I updated the resource from the new github then there was an update here for the interface. Can someone help?

**Comment by camonwii** [comment]
![image](https://user-images.githubusercontent.com/50628163/126874066-eb444e9e-5902-4e09-88e3-70ed64d9cd23.png)
![image](https://user-images.githubusercontent.com/50628163/126874081-06e7823b-388e-4540-8c2e-f0f0336e0445.png)


And that's when there's people on the server.

**Comment by camonwii** [comment]
Tried reinstalling it all again, no luck.

**Comment by TGRHavoc** [comment]
Have you tried clearing your browser's cache and trying to connect to it again?
If not then, can I ask you send me the URL to the interface so I can do some debugging on your particular setup?
You can send it to the email that's associated with my github account (jordan (at) my domain).

**Comment by camonwii** [comment]
> Have you tried clearing your browser's cache and trying to connect to it again?
> If not then, can I ask you send me the URL to the interface so I can do some debugging on your particular setup?
> You can send it to the email that's associated with my github account (jordan (at) my domain).
> The earliest I will be able to have a look will be tomorrow when I get some free time 😄

Cleared the cache, no help. I'll send you the link in your email.

**Comment by TGRHavoc** [comment]
Just remembered that I changed the manifest for the resource in the last update.
If anyone else is having these issues please do the following:

- Copy the `example_client` folder to `client` (this will allow you to update the resource without losing any changes to the client you make). 
- Head on into the manifest file (fxmanifest.lua or whatever the latest version is called) and uncomment the client files.

The manifest file should contain
```lua
client_script "client/*.lua"
exports {
     "reverseWeaponHash", "reverseVehicleHash", "reverseStreetHash",
     "reverseZoneHash", "reverseAreaHash"
}
```

**Comment by camonwii** [comment]
Yep thanks. Fixed it :)
