### ISSUE TITLE
Error in config

### ISSUE THREAD

**Issue by StrikersGamingTV** [TGRHavoc/live_map-interface#78]
Failed to fetch,

I set up my config this is my config, and i renamed it to config.json, also put it in var/www/html cause I am using apache to host it.

{
    "debug": false,
    "tileDirectory": "images/tiles",
    "iconDirectory": "images/icons",
    "showIdentifiers": false,
    "groupPlayers": true, // Wether the map should group players together into "clusters" or not.
    "defaults": { // If a server doesn't have the key-value set, it will fallback to these values
        "ip": "194.34.229.114", // Make sure this is the PUBLIC IP of the FIVEM server
        "socketPort": "30121" // Set to the port that you set in the "socket_port" convar (if different to the one in the config)
    },
    "servers": {
        "Default server 1": {}, // The config values are above, no need to write them again
        "Only IP changed": { // Only the IP is different for this server. So, change it
            "ip": "194.34.229.114"
        },
        "Everything is different": {
            "ip": "10.10.0.1",
            "socketPort": "60121"
        },
        "Reverse Proxy Example": {
            "reverseProxy": { // If you have knowledge on how to set up a "reverse proxy" for your webserver and want to keep the map on a secure connection, set the values below.
                "socket": "wss://example.com", // The secure, proxied url for the socket connection
                "blips": "https://example.com/server1/blips.json" // The secure, proxied url for the blip file
            }
        }
    },
    "maps": [
        {
            "name": "Normal",
            "url": "{tileDirectory}/normal/minimap_sea_{y}_{x}.png",
            "minZoom": -2 // Set lower to zoom out more
        },
        {
            "name": "Postal",
            "url": "{tileDirectory}/postal/minimap_sea_{y}_{x}.png",
            "minZoom": -5 // Since this is 3 times bigger, just remove 3 from the default minZoom
        }
    ]
}

**Comment by TGRHavoc** [comment]
Please make sure the interface isn't being hosted over HTTPS. Or, if it is, use a reverse proxy :)

**Comment by StrikersGamingTV** [comment]
it cannot be I don't have a ssl domain

**Comment by StrikersGamingTV** [comment]
what version is most stable and what version should I use

**Comment by TGRHavoc** [comment]
The latest versions should work fine?

Interface: 4.1.5 
Resource: 3.1.2

**Comment by StrikersGamingTV** [comment]
okay thank you

**Comment by StrikersGamingTV** [comment]
I can't test it at all to see the issue, but if you wouldn't mind checking both my tries http://194.34.229.114 and https://jsrp.000webhostapp.com

**Comment by TGRHavoc** [comment]
On mobile at the moment mate. Can only do limited stuff. It looks like the main page is broken for some reason. I won't be back at my PC to fully test until Monday 16th...

For now, you might be able to rename "debug.html" to "index.html" as a temporary fix.

**Comment by StrikersGamingTV** [comment]
I renamed it and I still have just v0.0 should I check with another member

**Comment by StrikersGamingTV** [comment]
nvm I see the map now, but I have no players in it?

**Comment by StrikersGamingTV** [comment]
I have 4 people on server, and I see no one? I am connected btw

**Comment by StrikersGamingTV** [comment]
only issue now is that I see no one in server

**Comment by TGRHavoc** [comment]
> 
> 
> only issue now is that I see no one in server

Make sure you've enabled the latest client script. 

Like it says in the readme:

[Now, you can enable the built-in client. Copy the example_client folder to client (this will allow you to update the resource without losing any changes to the client you make). Now, head on into the manifest file (fxmanifest.lua or whatever the latest version is called) and uncomment the client files.](https://github.com/TGRHavoc/live_map#how-to-install)

**Comment by StrikersGamingTV** [comment]
do I need to restart server first, I removed the comments out of fxmanifest do I need to do anything else?

**Comment by TGRHavoc** [comment]
> do I need to restart server first, I removed the comments out of fxmanifest do I need to do anything else?

Uncomment them, run `refresh` or whatever the command is for FiveM. Then, just `restart live_map`.

**Comment by StrikersGamingTV** [comment]
I was stupid and didn't rename example_client to client, everything is now working, thank you for all the help Havoc
