### ISSUE TITLE
Uncaught Error: Cannot find module './init.js'

### ISSUE THREAD

**Issue by matsn0w** [TGRHavoc/live_map-interface#79]
**Describe the bug**
Getting an error in the console when visiting index.html, page is not working properly. debug.html is working fine.

**To Reproduce**
1. Download release 4.1.5 from [here](https://github.com/TGRHavoc/live_map-interface/archive/refs/tags/v4.1.5.zip)
2. Go to index.html
3. Watch the browser console

**Expected behavior**
Find the needed filesssss and wooooork XD

**Screenshots**
![image](https://user-images.githubusercontent.com/15019582/130374833-0f4b7dc1-7dda-4eed-ac79-f79131c160b1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Browser: Microsoft Edge
 - Version: 92.0.902.78 

**Possible Solution**
I guess main.js isn't compiled properly?

**Additional context/Screenshots**
Tried doing the same with v4.1.4, that was working perfectly fine ;)

**Comment by TGRHavoc** [comment]
Think it was Browserify that was causing the build to come out corrupt (even though I haven't changed any of the config).

So, i've moved over to [Parcel.JS](https://parceljs.org/) for bundling the main code together. Sticking with gulp as the build system (and concating the parcel bundle with the vendor files for a single JS file).

Should be fixed with next release :)

**Comment by TGRHavoc** [comment]
@matsn0w If you want to test https://github.com/TGRHavoc/live_map-interface/releases/tag/v4.1.6 for me and make sure it works on your system, that would be awesome 😄

**Comment by TGRHavoc** [comment]
@all-contributors please add @matsn0w for bug

**Comment by matsn0w** [comment]
> @matsn0w If you want to test https://github.com/TGRHavoc/live_map-interface/releases/tag/v4.1.6 for me and make sure it works on your system, that would be awesome 😄

Like a charmio! Thanks a lot :)
