### ISSUE TITLE
Blips persist after switching servers

### ISSUE THREAD

**Issue by matsn0w** [TGRHavoc/live_map-interface#81]
**Describe the bug**
When switching between two servers, the blips of the 'old' server remain visible on the map.

**To Reproduce**
1. Add two servers to `config.js`
2. View the map of server 1
3. Switch to server 2
4. See both blip files merged together

**Expected behavior**
The blips of server 1 should be removed, only the blips of server 2 should be visible.

**Screenshots**
Server 1:
![image](https://user-images.githubusercontent.com/15019582/130926455-84c59f33-b239-4790-a3ed-fcc0c1a20482.png)

Switch to server 2:
![image](https://user-images.githubusercontent.com/15019582/130926727-95fdddb0-24ee-492a-8fc2-64dec0bd1f16.png)

Refresh of server 2:
![image](https://user-images.githubusercontent.com/15019582/130927099-58742c3b-5ed4-4c3d-a043-f3d3efae1e3e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Browser: Microsoft Edge
 - Version: 92.0.902.78

**Possible Solution**
Some kind of refresh ;)

**Additional context/Screenshots**
Tried Chrome as well, same issue.

**Comment by TGRHavoc** [comment]
Sorry for the late response on this. I didn't have as much spare time as usual due to work. Should be fixed though ❤️

**Comment by matsn0w** [comment]
> Sorry for the late response on this. I didn't have as much spare time as usual due to work. Should be fixed though ❤️

No worries, thanks for the hard work!
