### ISSUE TITLE
No Players Shown on Map

### ISSUE THREAD

**Issue by Flo122** [TGRHavoc/live_map-interface#87]
I did everything you wrote at the Readme and the How To Install last Version was working now its not working

**Comment by TGRHavoc** [comment]
Only thing I can suggest is to ask a developer to add a bunch of prints or Citizen.Trace's in the client files and make sure that the data is being updated and sent to the server.

**Comment by TGRHavoc** [comment]
Marking as needs repro because I cannot seem to reproduce myself.

**Comment by TGRHavoc** [comment]
Closing as I cannot reproduce and it's been a while.
