### ISSUE TITLE
Cant access Websocket

### ISSUE THREAD

**Issue by Kiba-Wolf** [TGRHavoc/live_map-interface#89]
**Describe the bug**
The Website dosnt connect to my server. I try to reinstall all needet skripts but still no connection.
(see screenshots) i try everithing last time everything works well but now it dont. I made everithing like it shows on the github pages.  the only thing i need to change is the port but that should be a problem or?

I dont have a Https i have a http server 

**Screenshots**

![livemap 4](https://user-images.githubusercontent.com/76842680/138553792-cba8a189-54cd-4a5e-ae51-934b1963994a.PNG)
![livemap2](https://user-images.githubusercontent.com/76842680/138553793-bd490559-4207-428c-a870-ddda3c17b0b6.PNG)
![livemap 1](https://user-images.githubusercontent.com/76842680/138553794-7b2c6bba-78de-4585-9d9d-28d3c8e6a44d.PNG)
![livemap 3](https://user-images.githubusercontent.com/76842680/138553795-2e01423a-afce-4d88-9ec3-82f6c795efd3.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [OperaGX]
 - Version [Latest]

**Comment by TGRHavoc** [comment]
If you want to use HTTPS then, make sure you set up the "reverseProxy" in the config with the nucleus URLs.

If you don't want to use this then you will have to change the `ip` and `socketPort` to your external IP for the server so that others can also connect to it.

**Comment by Kiba-Wolf** [comment]
It is both on localhost i had the port set to 30122 because i have a secound server running on my vps. I stop the secound server and put all back to 30121 and now everything is back to normal

**Comment by TGRHavoc** [comment]
Most likely was a cache issue in your browser. When you change a value in the config hard-refresh (CTRL+F5) and it should update.

**Comment by Kiba-Wolf** [comment]
Ok thanks for helping
