### ISSUE TITLE
cors issue 

### ISSUE THREAD

**Issue by jacobharr24** [TGRHavoc/live_map-interface#91]
it states this in the inspect: Access to fetch at 'https://monitor-lpzan32looa5zese5nd7ufps7mn4fta5.users.cfx.re/blips' from origin 'https://livemap.hopenetworks.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by jacobharr24** [comment]
if u have problem contact me on discord i will be willing to help  Jacobharr2 | Hope Networks#0421

**Comment by TGRHavoc** [comment]
Or, they could just `set livemap_access_control "*"` in their server config for the resource. Replacing the * with their website (e.g. `https://livemap.hopenetworks.net`)
