### ISSUE TITLE
no player markers

### ISSUE THREAD

**Issue by StrikersGamingTV** [TGRHavoc/live_map-interface#94]
new server that I dev for NSRP 194.34.229.43, no players are popping up and the blips are, proper server, I changed example client to client. it seems hella delayed because after 2 minutes 2 player count finally pops up.

**Comment by TGRHavoc** [comment]
What about when you have the debug level set to all in the server.cfg? You should see when the resource wants to send the data to the interface etc. Might be able to tell you whether it's a network issue (slow connection) or the interface itself.

Are you using the Nucleus proxy?
Are you using the master branch or develop branch for the interface (develop is a lot more unstable so, try master if you're not already on it).

**Comment by StrikersGamingTV** [comment]
I tried turning off nucleus it was on by default, all I did was delete everything is us or whatever the second server, changed the example client to client yes in fxmanifest aswell, yes I generated blips, other then that default

**Comment by StrikersGamingTV** [comment]
/var/www/html/config.json

{
    "debug": false,
    "tileDirectory": "images/tiles",
    "iconDirectory": "images/icons",
    "showIdentifiers": false,
    "groupPlayers": true, // Wether the map should group players together into "clusters" or not.
    "defaults": { // If a server doesn't have the key-value set, it will fallback to these values
        "ip": "194.34.229.43", // Make sure this is the PUBLIC IP of the FIVEM server
        "socketPort": "30121" // Set to the port that you set in the "socket_port" convar (if different to the one in the config)
    },
    "servers": {
        "Default server 1": {}, // The config values are above, no need to write them again
        "Only IP changed": { // Only the IP is different for this server. So, change it
            "ip": "194.34.229.43"
        },
        "Everything is different": {
            "ip": "10.10.0.1",
            "socketPort": "60121"
        },
        "Reverse Proxy Example": {
            "reverseProxy": { // If you have knowledge on how to set up a "reverse proxy" for your webserver and want to keep the map on a secure connection, set the values below.
                "socket": "wss://example.com", // The secure, proxied url for the socket connection
                "blips": "https://example.com/server1/blips.json" // The secure, proxied url for the blip file
            }
        }
    },
    "maps": [
        {
            "name": "Normal",
            "url": "{tileDirectory}/normal/minimap_sea_{y}_{x}.png",
            "minZoom": -2 // Set lower to zoom out more
        },
        {
            "name": "Postal",
            "url": "{tileDirectory}/postal/minimap_sea_{y}_{x}.png",
            "minZoom": -5 // Since this is 3 times bigger, just remove 3 from the default minZoom
        }
    ]
}

**Comment by StrikersGamingTV** [comment]
/FiveM/server-data/server.cfg

set socket_port 30121
set livemap_debug "warn" # "[all]" 'trace', 'debug', 'info', 'warn', 'error', 'fatal', 'off'
set blip_file "server/blips.json"
set livemap_access_control "*"
set livemap_use_nucleus false # Allow livemap to set up a secure reverseProxy using the Nucleus project

**Comment by StrikersGamingTV** [comment]
![image](https://user-images.githubusercontent.com/72888419/144784265-831f2638-8656-448c-b33a-c8395d7a7484.png)

the whole client shit

**Comment by StrikersGamingTV** [comment]
Still not working, please help when possible

**Comment by StrikersGamingTV** [comment]
my livemap is working I just came on today and it updated to 4.1.8 and now it works
